### ISSUE TITLE
translate functions/variables names to English

### ISSUE THREAD

**Issue by alessandroargentieri** [f4rezer0/free-time-marker#2]
Since the programming language is composed of pseudo English words chained together, you will see things like:
```
ss.getSheetByName()
```
but mixed with functions and variables in Italian like:
```
function inviaFoglioMesePrecedente() {
   var dataOraOdierna = new Date();
```
With this issue I propose to switch the whole codebase to English (except the contents of the variables like "In allegato trovi il foglio del mese precedente." because addressing an Italian pool of users).

**Comment by willskymaker** [comment]
Solved
